/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashless;

import tools.WebcamCapture;
import tools.Camera;
import cls.Ticket;
import db.queryPayment;
import db.queryTicket;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Hades
 */
public class Hexapark_backup2 extends javax.swing.JFrame {

    private Ticket tkt = new Ticket();
    private CardLayout cl;
    private CardLayout cl2;
    private CardLayout cl3;
    SimpleDateFormat entranceTime = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
    SimpleDateFormat exitTime = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");

    /**
     * Creates new form Main
     */
    public Hexapark_backup2() {
        initComponents();
        //setLocationRelativeTo(this);
        makeFrameFullSize(this);
    }

    private void makeFrameFullSize(JFrame aFrame) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        aFrame.setSize(screenSize.width, screenSize.height);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jPanel13 = new javax.swing.JPanel();
        panelStep = new javax.swing.JPanel();
        panelStep1 = new javax.swing.JPanel();
        img_stepScan = new javax.swing.JLabel();
        panelStep2 = new javax.swing.JPanel();
        img_stepInfo = new javax.swing.JLabel();
        panelStep3 = new javax.swing.JPanel();
        img_stepPayment = new javax.swing.JLabel();
        panelStep4 = new javax.swing.JPanel();
        img_stepFinish = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        panelScanBarcode = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        panelParkingInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tkt_barcode = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tkt_gate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tkt_entrance = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tkt_noPol = new javax.swing.JTextField();
        panelImage1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        panelImage2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        panelUpdateNoPol = new javax.swing.JPanel();
        panelMenuParkingInfo = new javax.swing.JPanel();
        btnChangePolNum = new javax.swing.JButton();
        btnPaymentProcess = new javax.swing.JButton();
        btnCancelInfo = new javax.swing.JButton();
        panelKonfirmUpdate = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panelPayment = new javax.swing.JPanel();
        panelInfoPayment = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTrx_Gate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTrx_PolNum = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTrx_type = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTrx_entrance = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTrx_Exit = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTrx_Price = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelMenuPayment = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnCancelPayment = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        panelFinish = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panelAccountBalanceInfo = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtFin_Price = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtFin_balance = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));

        panelStep.setLayout(new java.awt.CardLayout());

        img_stepScan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Scan Barcode.png"))); // NOI18N

        javax.swing.GroupLayout panelStep1Layout = new javax.swing.GroupLayout(panelStep1);
        panelStep1.setLayout(panelStep1Layout);
        panelStep1Layout.setHorizontalGroup(
            panelStep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
            .addGroup(panelStep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStep1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(img_stepScan, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelStep1Layout.setVerticalGroup(
            panelStep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
            .addGroup(panelStep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStep1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(img_stepScan, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(277, Short.MAX_VALUE)))
        );

        panelStep.add(panelStep1, "cardScan");

        img_stepInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Info Parkir.png"))); // NOI18N

        javax.swing.GroupLayout panelStep2Layout = new javax.swing.GroupLayout(panelStep2);
        panelStep2.setLayout(panelStep2Layout);
        panelStep2Layout.setHorizontalGroup(
            panelStep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
            .addGroup(panelStep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStep2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(img_stepInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelStep2Layout.setVerticalGroup(
            panelStep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
            .addGroup(panelStep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStep2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(img_stepInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(277, Short.MAX_VALUE)))
        );

        panelStep.add(panelStep2, "cardInfo");

        img_stepPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pembayaran.png"))); // NOI18N

        javax.swing.GroupLayout panelStep3Layout = new javax.swing.GroupLayout(panelStep3);
        panelStep3.setLayout(panelStep3Layout);
        panelStep3Layout.setHorizontalGroup(
            panelStep3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
            .addGroup(panelStep3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStep3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(img_stepPayment, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelStep3Layout.setVerticalGroup(
            panelStep3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
            .addGroup(panelStep3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStep3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(img_stepPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(277, Short.MAX_VALUE)))
        );

        panelStep.add(panelStep3, "cardPayment");

        img_stepFinish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Selesai.png"))); // NOI18N

        javax.swing.GroupLayout panelStep4Layout = new javax.swing.GroupLayout(panelStep4);
        panelStep4.setLayout(panelStep4Layout);
        panelStep4Layout.setHorizontalGroup(
            panelStep4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
            .addGroup(panelStep4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStep4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(img_stepFinish, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelStep4Layout.setVerticalGroup(
            panelStep4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
            .addGroup(panelStep4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStep4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(img_stepFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(277, Short.MAX_VALUE)))
        );

        panelStep.add(panelStep4, "cardFinish");

        panelMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelMain.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCAN TIKET ANDA");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("How to scan barcode (Image Unavailable)");

        jButton5.setText("(Dummy) Generate");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelScanBarcodeLayout = new javax.swing.GroupLayout(panelScanBarcode);
        panelScanBarcode.setLayout(panelScanBarcodeLayout);
        panelScanBarcodeLayout.setHorizontalGroup(
            panelScanBarcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScanBarcodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelScanBarcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelScanBarcodeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        panelScanBarcodeLayout.setVerticalGroup(
            panelScanBarcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScanBarcodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap())
        );

        panelMain.add(panelScanBarcode, "card_scan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INFO KENDARAAN ANDA");

        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 20, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setText("KODE TIKET");
        jPanel1.add(jLabel3);

        tkt_barcode.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tkt_barcode.setText("029387429834090215");
        jPanel1.add(tkt_barcode);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setText("PINTU MASUK");
        jPanel1.add(jLabel4);

        tkt_gate.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tkt_gate.setText("0");
        jPanel1.add(tkt_gate);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setText("JAM MASUK");
        jPanel1.add(jLabel5);

        tkt_entrance.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tkt_entrance.setText("06:30:32 21/10/2017");
        jPanel1.add(tkt_entrance);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setText("NOMOR POLISI");
        jPanel1.add(jLabel6);

        tkt_noPol.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tkt_noPol.setText("BG 2509 QO");
        tkt_noPol.setFocusable(false);
        jPanel1.add(tkt_noPol);

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
            .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelInfoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
            .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelInfoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelImage1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Image Unavailable");

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelImage2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Image Unavailable");

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelUpdateNoPol.setLayout(new java.awt.CardLayout());

        panelMenuParkingInfo.setLayout(new java.awt.GridLayout(1, 3, 30, 0));

        btnChangePolNum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChangePolNum.setText("UBAH NO. POLISI");
        btnChangePolNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePolNumActionPerformed(evt);
            }
        });
        panelMenuParkingInfo.add(btnChangePolNum);

        btnPaymentProcess.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPaymentProcess.setText("PROSES PEMBAYARAN");
        btnPaymentProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentProcessActionPerformed(evt);
            }
        });
        panelMenuParkingInfo.add(btnPaymentProcess);

        btnCancelInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelInfo.setText("BATAL");
        btnCancelInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelInfoActionPerformed(evt);
            }
        });
        panelMenuParkingInfo.add(btnCancelInfo);

        panelUpdateNoPol.add(panelMenuParkingInfo, "card1");

        panelKonfirmUpdate.setLayout(new java.awt.GridLayout(1, 2, 100, 0));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Selesai");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelKonfirmUpdate.add(jButton3);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("Batal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelKonfirmUpdate.add(jButton4);

        panelUpdateNoPol.add(panelKonfirmUpdate, "card2");

        javax.swing.GroupLayout panelParkingInfoLayout = new javax.swing.GroupLayout(panelParkingInfo);
        panelParkingInfo.setLayout(panelParkingInfoLayout);
        panelParkingInfoLayout.setHorizontalGroup(
            panelParkingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParkingInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelParkingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelUpdateNoPol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParkingInfoLayout.createSequentialGroup()
                        .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParkingInfoLayout.createSequentialGroup()
                        .addGap(0, 710, Short.MAX_VALUE)
                        .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelParkingInfoLayout.setVerticalGroup(
            panelParkingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParkingInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelParkingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelParkingInfoLayout.createSequentialGroup()
                        .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelUpdateNoPol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelMain.add(panelParkingInfo, "card_parkingInfo");

        jPanel7.setLayout(new java.awt.GridLayout(6, 2));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel8.setText("PINTU MASUK");
        jPanel7.add(jLabel8);

        txtTrx_Gate.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtTrx_Gate.setText("1");
        jPanel7.add(txtTrx_Gate);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel9.setText("NOMOR POLISI");
        jPanel7.add(jLabel9);

        txtTrx_PolNum.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtTrx_PolNum.setText("BG 2509 QO");
        jPanel7.add(txtTrx_PolNum);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel10.setText("JENIS TARIF");
        jPanel7.add(jLabel10);

        txtTrx_type.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtTrx_type.setText("Mobil");
        jPanel7.add(txtTrx_type);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel11.setText("JAM MASUK");
        jPanel7.add(jLabel11);

        txtTrx_entrance.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtTrx_entrance.setText("06:30:15 21/10/2017");
        jPanel7.add(txtTrx_entrance);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel12.setText("JAM KELUAR");
        jPanel7.add(jLabel12);

        txtTrx_Exit.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtTrx_Exit.setText("06:30:15 21/10/2017");
        jPanel7.add(txtTrx_Exit);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel13.setText("TOTAL BIAYA");
        jPanel7.add(jLabel13);

        txtTrx_Price.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtTrx_Price.setText("Rp. 11.000.-");
        jPanel7.add(txtTrx_Price);

        javax.swing.GroupLayout panelInfoPaymentLayout = new javax.swing.GroupLayout(panelInfoPayment);
        panelInfoPayment.setLayout(panelInfoPaymentLayout);
        panelInfoPaymentLayout.setHorizontalGroup(
            panelInfoPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelInfoPaymentLayout.setVerticalGroup(
            panelInfoPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TRANSAKSI KENDARAAN");

        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 300, 0));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("(Dummy) Tap Card");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        btnCancelPayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCancelPayment.setText("BATAL");
        btnCancelPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelPaymentActionPerformed(evt);
            }
        });
        jPanel5.add(btnCancelPayment);

        javax.swing.GroupLayout panelMenuPaymentLayout = new javax.swing.GroupLayout(panelMenuPayment);
        panelMenuPayment.setLayout(panelMenuPaymentLayout);
        panelMenuPaymentLayout.setHorizontalGroup(
            panelMenuPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelMenuPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMenuPaymentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1018, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelMenuPaymentLayout.setVerticalGroup(
            panelMenuPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
            .addGroup(panelMenuPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("SILAKAN TAP KARTU PEMBAYARAN ANDA !");

        javax.swing.GroupLayout panelPaymentLayout = new javax.swing.GroupLayout(panelPayment);
        panelPayment.setLayout(panelPaymentLayout);
        panelPaymentLayout.setHorizontalGroup(
            panelPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMenuPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPaymentLayout.createSequentialGroup()
                        .addGap(0, 179, Short.MAX_VALUE)
                        .addComponent(panelInfoPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelPaymentLayout.setVerticalGroup(
            panelPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInfoPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelMenuPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelMain.add(panelPayment, "card_payment");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("TERIMA KASIH");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("WAKTU ANDA 15 MENIT UNTUK KELUAR DARI GERBANG !!!");

        jPanel12.setLayout(new java.awt.GridLayout(2, 2));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel16.setText("TOTAL BIAYA");
        jPanel12.add(jLabel16);

        txtFin_Price.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtFin_Price.setText("Rp. 11.000.-");
        jPanel12.add(txtFin_Price);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel17.setText("SISA SALDO");
        jPanel12.add(jLabel17);

        txtFin_balance.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtFin_balance.setText("Rp. 154.000.-");
        jPanel12.add(txtFin_balance);

        javax.swing.GroupLayout panelAccountBalanceInfoLayout = new javax.swing.GroupLayout(panelAccountBalanceInfo);
        panelAccountBalanceInfo.setLayout(panelAccountBalanceInfoLayout);
        panelAccountBalanceInfoLayout.setHorizontalGroup(
            panelAccountBalanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelAccountBalanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAccountBalanceInfoLayout.createSequentialGroup()
                    .addContainerGap(217, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        panelAccountBalanceInfoLayout.setVerticalGroup(
            panelAccountBalanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
            .addGroup(panelAccountBalanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAccountBalanceInfoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFinishLayout = new javax.swing.GroupLayout(panelFinish);
        panelFinish.setLayout(panelFinishLayout);
        panelFinishLayout.setHorizontalGroup(
            panelFinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinishLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAccountBalanceInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFinishLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelFinishLayout.setVerticalGroup(
            panelFinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinishLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelAccountBalanceInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelMain.add(panelFinish, "card_finish");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(298, Short.MAX_VALUE)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelStep, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1082, Short.MAX_VALUE)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelStep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String code = JOptionPane.showInputDialog("Barcode :");
        if (!code.equals("")) {
            //Isi Objek Tiket dengan data dari database
            getDataTicket(code);
            //Tampil Info Parkit
            cl = (CardLayout) panelMain.getLayout();
            cl.show(panelMain, "card_parkingInfo");
            cl2 = (CardLayout) panelStep.getLayout();
            cl2.show(panelStep, "cardInfo");
        } else {
            System.out.println("Barcode tidak ditemukan");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCancelInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelInfoActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) panelMain.getLayout();
        cl.show(panelMain, "card_scan");
        cl2 = (CardLayout) panelStep.getLayout();
        cl2.show(panelStep, "cardScan");
    }//GEN-LAST:event_btnCancelInfoActionPerformed

    private void btnPaymentProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentProcessActionPerformed
        // TODO add your handling code here:
        //Proses data tiket menjadi informasi pembayaran
        getDataPayment(tkt.getBarcode());
        cl = (CardLayout) panelMain.getLayout();
        cl.show(panelMain, "card_payment");
        cl2 = (CardLayout) panelStep.getLayout();
        cl2.show(panelStep, "cardPayment");
    }//GEN-LAST:event_btnPaymentProcessActionPerformed

    private void btnCancelPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelPaymentActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) panelMain.getLayout();
        cl.show(panelMain, "card_parkingInfo");
        cl2 = (CardLayout) panelStep.getLayout();
        cl2.show(panelStep, "cardInfo");
    }//GEN-LAST:event_btnCancelPaymentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) panelMain.getLayout();
        cl.show(panelMain, "card_finish");
        cl2 = (CardLayout) panelStep.getLayout();
        cl2.show(panelStep, "cardFinish");
        try {
            //Capture Webcam (2 Option with different Library)
            //Pilihan 1
            //boolean c = new Camera().capture(tkt.getBarcode());
            //Pilihan 2
            new WebcamCapture().capture(tkt.getBarcode());
        } catch (IOException ex) {
            Logger.getLogger(Hexapark_backup2.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtFin_Price.setText("Rp. " + "45.000" + ".-");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnChangePolNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePolNumActionPerformed
        // TODO add your handling code here:
        tkt_noPol.setFocusable(true);
        cl3 = (CardLayout) panelUpdateNoPol.getLayout();
        cl3.show(panelUpdateNoPol, "card2");
    }//GEN-LAST:event_btnChangePolNumActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) panelMain.getLayout();
        cl.show(panelMain, "card_scan");
        cl2 = (CardLayout) panelStep.getLayout();
        cl2.show(panelStep, "cardScan");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Update Nomor Polisi Kendaraan
        int updatePolNum = new queryTicket().updatePolNum(tkt.getBarcode(), tkt_noPol.getText());
        if (updatePolNum != 0) {
            tkt.setLicenseNumber(tkt_noPol.getText());
            JOptionPane.showMessageDialog(null, "Nomor Polisi Berhasil Diperbarui");
        } else {
            JOptionPane.showMessageDialog(null, "Nomor Polisi Gagal Diperbarui, Silakan Hubungi Pengelola Layanan");
        }
        cl3 = (CardLayout) panelUpdateNoPol.getLayout();
        cl3.show(panelUpdateNoPol, "card1");
        tkt_noPol.setFocusable(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        tkt_noPol.setFocusable(false);
        tkt_noPol.setText(tkt.getLicenseNumber());
        JOptionPane.showMessageDialog(null, "Update Nomor Polisi Dibatalkan");
        cl3 = (CardLayout) panelUpdateNoPol.getLayout();
        cl3.show(panelUpdateNoPol, "card1");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void getDataTicket(String code) {
        tkt = new queryTicket().getData(code);
        tkt_barcode.setText(code);
        tkt_gate.setText(Integer.toString(tkt.getEntranceGate()));
        tkt_entrance.setText(tkt.getEntranceTime());
        tkt_noPol.setText(tkt.getLicenseNumber());

        //Testing Cek Harga
        queryPayment qp = new queryPayment();
        int[] tarifInfo = qp.getPriceInfo(tkt);
        System.out.println("Tarif Info");
        System.out.print(tarifInfo[0] + " ");
        System.out.print(tarifInfo[1] + " ");
        System.out.print(tarifInfo[2] + " ");
        System.out.println(tarifInfo[3]);
        int harga = 0;
        if (qp.cekMember(tkt.getBarcode()).equalsIgnoreCase("YES")) {
            System.out.println("Member Mah Gratis");
        } else if (tkt.getTarifTypes().equalsIgnoreCase("I A")) {
            System.out.println(tkt.getTarifTypes());
        } else if (tkt.getTarifTypes().equalsIgnoreCase("I B")) {
            System.out.println(tkt.getTarifTypes());
        } else if (tkt.getTarifTypes().equalsIgnoreCase("I C")) {
            System.out.println(tkt.getTarifTypes());
        } else if (tkt.getTarifTypes().equalsIgnoreCase("III A")) {
            System.out.println(tkt.getTarifTypes());
            harga = qp.determinePriceInap(tkt.getEntranceTime(), tkt.getExitTime(), tarifInfo[1], tarifInfo[2], tarifInfo[0]);
        } else if (tkt.getTarifTypes().equalsIgnoreCase("IV")) {
            System.out.println(tkt.getTarifTypes());
            harga = qp.determinePriceInap(tkt.getEntranceTime(), tkt.getExitTime(), tarifInfo[1], tarifInfo[2], tarifInfo[0]);
        }
        System.out.println(harga);
    }

    private void getDataPayment(String code) {
        txtTrx_Gate.setText(Integer.toString(tkt.getEntranceGate()));
        txtTrx_PolNum.setText(tkt.getLicenseNumber());
        txtTrx_type.setText(tkt.getVehicleTypes());
        txtTrx_entrance.setText(tkt.getEntranceTime());
        //Set Date Exit
        Calendar dateNow = Calendar.getInstance();
        Date skr = new Date();
        dateNow.setTime(skr);
        txtTrx_Exit.setText(exitTime.format(skr));
        txtTrx_Price.setText("RP." + tkt.getPrice() + ".-");
    }

    public class BillPrintable implements Printable {

        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex)
                throws PrinterException {

            int result = NO_SUCH_PAGE;
            if (pageIndex == 0) {

                Graphics2D g2d = (Graphics2D) graphics;

                double width = pageFormat.getImageableWidth();

                g2d.translate((int) pageFormat.getImageableX(), (int) pageFormat.getImageableY());

                ////////// code by alqama//////////////
                FontMetrics metrics = g2d.getFontMetrics(new Font("Arial", Font.BOLD, 7));
                //    int idLength=metrics.stringWidth("000000");
                //int idLength=metrics.stringWidth("00");
                int idLength = metrics.stringWidth("000");
                int amtLength = metrics.stringWidth("000000");
                int qtyLength = metrics.stringWidth("00000");
                int priceLength = metrics.stringWidth("000000");
                int prodLength = (int) width - idLength - amtLength - qtyLength - priceLength - 17;

                //    int idPosition=0;
                //    int productPosition=idPosition + idLength + 2;
                //    int pricePosition=productPosition + prodLength +10;
                //    int qtyPosition=pricePosition + priceLength + 2;
                //    int amtPosition=qtyPosition + qtyLength + 2;
                int productPosition = 0;
                int discountPosition = prodLength + 5;
                int pricePosition = discountPosition + idLength + 10;
                int qtyPosition = pricePosition + priceLength + 4;
                int amtPosition = qtyPosition + qtyLength;

                try {
                    /*Draw Header*/
                    int y = 20;
                    int yShift = 10;
                    int headerRectHeight = 15;
                    int headerRectHeighta = 40;

                    ///////////////// Product names Get ///////////
                    String nokarcis = tkt.getBarcode();
                    String jPark = tkt.getVehicleTypes();
                    String nopol = tkt.getLicenseNumber();
                    String tgl_masuk = tkt.getEntranceTime();
                    String tgl_keluar = tkt.getExitTime();
                    String pos_masuk = Integer.toString(tkt.getEntranceGate());
                    String pos_keluar = Integer.toString(tkt.getExitGate());
                    String lama = tkt.getEntranceTime();
                    String[] lamaSplit = lama.split(" :");
                    String total = Integer.toString(tkt.getPrice());
                    ///////////////// Product names Get ///////////

                    ///////////////// SET LAYOUT /////////////////
                    g2d.setFont(new Font("Monospaced", Font.PLAIN, 9));
                    g2d.drawString("-------------------------------------", 12, y);
                    y += yShift;
                    g2d.drawString("TANDA BUKTI PEMBAYARAN PARKIR", 12, y);
                    y += yShift;
                    g2d.drawString("       PRODEXA PARKING     ", 12, y);
                    y += yShift;
                    g2d.drawString("        BANDARA SMB II     ", 12, y);
                    y += yShift;
                    g2d.drawString("-------------------------------------", 12, y);
                    y += headerRectHeight;

                    g2d.drawString("-------------------------------------", 9, y);
                    y += yShift;
                    g2d.drawString(" Nomor Polisi: " + nopol + "/" + jPark + "   ", 9, y);
                    y += yShift;
                    g2d.drawString(" POS Masuk   : " + pos_masuk + "   ", 9, y);
                    y += yShift;
                    g2d.drawString(" Waktu Masuk : " + tgl_masuk + " ", 9, y);
                    y += yShift;
                    g2d.drawString(" POS Keluar  : " + pos_keluar + "   ", 9, y);
                    y += yShift;
                    g2d.drawString(" Waktu Keluar: " + tgl_keluar + " ", 9, y);
                    y += yShift;

                    if (lamaSplit.length == 4) {
                        g2d.drawString(" Lama        : " + lamaSplit[0] + "" + lamaSplit[1] + "   ", 9, y);
                        y += yShift;
                        g2d.drawString("                  " + lamaSplit[2] + "" + lamaSplit[3] + "   ", 9, y);
                        y += yShift;
                        System.out.print("" + lamaSplit[0]);
                        System.out.print("" + lamaSplit[1]);
                        System.out.print("" + lamaSplit[2]);
                        System.out.print("" + lamaSplit[3]);
                    } else if (lamaSplit.length == 3) {
                        g2d.drawString(" Lama        : " + lamaSplit[0] + "" + lamaSplit[1] + "   ", 9, y);
                        y += yShift;
                        g2d.drawString("                  " + lamaSplit[2] + "                   ", 9, y);
                        y += yShift;
                        System.out.print("" + lamaSplit[0]);
                        System.out.print("" + lamaSplit[1]);
                        System.out.print("" + lamaSplit[2]);
                    } else if (lamaSplit.length == 2) {
                        g2d.drawString(" Lama        : " + lamaSplit[0] + "" + lamaSplit[1] + "   ", 9, y);
                        y += yShift;
                        System.out.print("" + lamaSplit[0]);
                        System.out.print("" + lamaSplit[1]);
                    } else if (lamaSplit.length == 1) {
                        g2d.drawString(" Lama        : " + lamaSplit[0] + "                   ", 9, y);
                        y += yShift;
                        System.out.print("" + lamaSplit[0]);
                    }

                    g2d.drawString(" Total       : " + total + "   ", 9, y);
                    y += yShift;
                    g2d.drawString("-------------------------------------", 10, y);
                    y += headerRectHeight;
                    g2d.drawString("-------------------------------------", 10, y);
                    y += yShift;
                    g2d.drawString("      HATI HATI DIJALAN          ", 10, y);
                    y += yShift;
                    g2d.drawString("         TERIMA KASIH             ", 10, y);
                    y += yShift;
                    g2d.drawString("-------------------------------------", 10, y);
                    y += yShift;
                    g2d.drawString("                                     ", 10, y);
                    y += yShift;
                    g2d.drawString("                                     ", 10, y);
                    y += yShift;
                    g2d.drawString("                                     ", 10, y);
                    y += yShift;

                    g2d.setFont(new Font("Monospaced", Font.BOLD, 10));
                    g2d.drawString("", 30, y);
                    y += yShift;

                } catch (Exception r) {
                    r.printStackTrace();
                }

                result = PAGE_EXISTS;
            }
            return result;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hexapark_backup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hexapark_backup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hexapark_backup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hexapark_backup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hexapark_backup2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelInfo;
    private javax.swing.JButton btnCancelPayment;
    private javax.swing.JButton btnChangePolNum;
    private javax.swing.JButton btnPaymentProcess;
    private javax.swing.JLabel img_stepFinish;
    private javax.swing.JLabel img_stepInfo;
    private javax.swing.JLabel img_stepPayment;
    private javax.swing.JLabel img_stepScan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel panelAccountBalanceInfo;
    private javax.swing.JPanel panelFinish;
    private javax.swing.JPanel panelImage1;
    private javax.swing.JPanel panelImage2;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelInfoPayment;
    private javax.swing.JPanel panelKonfirmUpdate;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMenuParkingInfo;
    private javax.swing.JPanel panelMenuPayment;
    private javax.swing.JPanel panelParkingInfo;
    private javax.swing.JPanel panelPayment;
    private javax.swing.JPanel panelScanBarcode;
    private javax.swing.JPanel panelStep;
    private javax.swing.JPanel panelStep1;
    private javax.swing.JPanel panelStep2;
    private javax.swing.JPanel panelStep3;
    private javax.swing.JPanel panelStep4;
    private javax.swing.JPanel panelUpdateNoPol;
    private javax.swing.JLabel tkt_barcode;
    private javax.swing.JLabel tkt_entrance;
    private javax.swing.JLabel tkt_gate;
    private javax.swing.JTextField tkt_noPol;
    private javax.swing.JLabel txtFin_Price;
    private javax.swing.JLabel txtFin_balance;
    private javax.swing.JLabel txtTrx_Exit;
    private javax.swing.JLabel txtTrx_Gate;
    private javax.swing.JLabel txtTrx_PolNum;
    private javax.swing.JLabel txtTrx_Price;
    private javax.swing.JLabel txtTrx_entrance;
    private javax.swing.JLabel txtTrx_type;
    // End of variables declaration//GEN-END:variables
}
