/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hexapark;

import camera.WebcamCapture;
import camera.Camera;
import cls.Ticket;
import db.queryPayment;
import db.queryTicket;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Hades
 */
public class Hexapark_backup extends javax.swing.JFrame {

    private Ticket tkt = new Ticket();
    private CardLayout cl;
    SimpleDateFormat entranceTime = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
    SimpleDateFormat exitTime = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");

    /**
     * Creates new form Main
     */
    public Hexapark_backup() {
        initComponents();
        //setLocationRelativeTo(this);
        makeFrameFullSize(this);
    }

    private void makeFrameFullSize(JFrame aFrame) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        aFrame.setSize(screenSize.width, screenSize.height);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jPanel13 = new javax.swing.JPanel();
        jToolBar_Step = new javax.swing.JToolBar();
        btn_scanTiket = new javax.swing.JButton();
        btn_parkingInfo = new javax.swing.JButton();
        btn_payment = new javax.swing.JButton();
        btn_finish = new javax.swing.JButton();
        jPanel_main = new javax.swing.JPanel();
        jPanel_scan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel_parkingInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tkt_barcode = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tkt_gate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tkt_entrance = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tkt_noPol = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnChangePolNum = new javax.swing.JButton();
        btnPaymentProcess = new javax.swing.JButton();
        btnCancelInfo = new javax.swing.JButton();
        jPanel4_payment = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTrx_Gate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTrx_PolNum = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTrx_type = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTrx_entrance = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTrx_Exit = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTrx_Price = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnCancelPayment = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel_finish = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtFin_Price = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtFin_balance = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));

        jToolBar_Step.setBorder(null);
        jToolBar_Step.setFloatable(false);
        jToolBar_Step.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar_Step.setRollover(true);
        jToolBar_Step.setMaximumSize(new java.awt.Dimension(280, 428));
        jToolBar_Step.setMinimumSize(new java.awt.Dimension(280, 428));
        jToolBar_Step.setPreferredSize(new java.awt.Dimension(280, 428));

        btn_scanTiket.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_scanTiket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_scan.png"))); // NOI18N
        btn_scanTiket.setText("Scan Tiket");
        btn_scanTiket.setFocusable(false);
        btn_scanTiket.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_scanTiket.setMaximumSize(new java.awt.Dimension(280, 107));
        btn_scanTiket.setMinimumSize(new java.awt.Dimension(280, 107));
        btn_scanTiket.setPreferredSize(new java.awt.Dimension(280, 107));
        jToolBar_Step.add(btn_scanTiket);

        btn_parkingInfo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_parkingInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_parkingInfo.png"))); // NOI18N
        btn_parkingInfo.setText("Info Parkir");
        btn_parkingInfo.setFocusable(false);
        btn_parkingInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_parkingInfo.setMaximumSize(new java.awt.Dimension(280, 107));
        btn_parkingInfo.setMinimumSize(new java.awt.Dimension(280, 107));
        btn_parkingInfo.setPreferredSize(new java.awt.Dimension(280, 107));
        jToolBar_Step.add(btn_parkingInfo);

        btn_payment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_payment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_payment.png"))); // NOI18N
        btn_payment.setText("Pembayaran");
        btn_payment.setFocusable(false);
        btn_payment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_payment.setMaximumSize(new java.awt.Dimension(280, 107));
        btn_payment.setMinimumSize(new java.awt.Dimension(280, 107));
        btn_payment.setPreferredSize(new java.awt.Dimension(280, 107));
        jToolBar_Step.add(btn_payment);

        btn_finish.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_finish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_finish.png"))); // NOI18N
        btn_finish.setText("Selesai");
        btn_finish.setFocusable(false);
        btn_finish.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_finish.setMaximumSize(new java.awt.Dimension(280, 107));
        btn_finish.setMinimumSize(new java.awt.Dimension(280, 107));
        btn_finish.setPreferredSize(new java.awt.Dimension(280, 107));
        jToolBar_Step.add(btn_finish);

        jPanel_main.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_main.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCAN TIKET ANDA");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Image Unavailable");

        jButton5.setText("(Dummy) Generate");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_scanLayout = new javax.swing.GroupLayout(jPanel_scan);
        jPanel_scan.setLayout(jPanel_scanLayout);
        jPanel_scanLayout.setHorizontalGroup(
            jPanel_scanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_scanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_scanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_scanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        jPanel_scanLayout.setVerticalGroup(
            jPanel_scanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_scanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap())
        );

        jPanel_main.add(jPanel_scan, "card_scan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INFO KENDARAAN ANDA");

        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 20, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setText("KODE TIKET");
        jPanel1.add(jLabel3);

        tkt_barcode.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tkt_barcode.setText("029387429834090215");
        jPanel1.add(tkt_barcode);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setText("PINTU MASUK");
        jPanel1.add(jLabel4);

        tkt_gate.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tkt_gate.setText("0");
        jPanel1.add(tkt_gate);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setText("JAM MASUK");
        jPanel1.add(jLabel5);

        tkt_entrance.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tkt_entrance.setText("06:30:32 21/10/2017");
        jPanel1.add(tkt_entrance);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setText("NOMOR POLISI");
        jPanel1.add(jLabel6);

        tkt_noPol.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tkt_noPol.setText("BG 2509 QO");
        jPanel1.add(tkt_noPol);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Image Unavailable");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Image Unavailable");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setLayout(new java.awt.GridLayout(1, 3, 30, 0));

        btnChangePolNum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnChangePolNum.setText("UBAH NO. POLISI");
        btnChangePolNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePolNumActionPerformed(evt);
            }
        });
        jPanel4.add(btnChangePolNum);

        btnPaymentProcess.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPaymentProcess.setText("PROSES PEMBAYARAN");
        btnPaymentProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentProcessActionPerformed(evt);
            }
        });
        jPanel4.add(btnPaymentProcess);

        btnCancelInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelInfo.setText("BATAL");
        btnCancelInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelInfoActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancelInfo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1018, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel_parkingInfoLayout = new javax.swing.GroupLayout(jPanel_parkingInfo);
        jPanel_parkingInfo.setLayout(jPanel_parkingInfoLayout);
        jPanel_parkingInfoLayout.setHorizontalGroup(
            jPanel_parkingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_parkingInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_parkingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_parkingInfoLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_parkingInfoLayout.createSequentialGroup()
                        .addGap(0, 710, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_parkingInfoLayout.setVerticalGroup(
            jPanel_parkingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_parkingInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_parkingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_parkingInfoLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_main.add(jPanel_parkingInfo, "card_parkingInfo");

        jPanel7.setLayout(new java.awt.GridLayout(6, 2));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel8.setText("PINTU MASUK");
        jPanel7.add(jLabel8);

        txtTrx_Gate.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtTrx_Gate.setText("1");
        jPanel7.add(txtTrx_Gate);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel9.setText("NOMOR POLISI");
        jPanel7.add(jLabel9);

        txtTrx_PolNum.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtTrx_PolNum.setText("BG 2509 QO");
        jPanel7.add(txtTrx_PolNum);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel10.setText("JENIS TARIF");
        jPanel7.add(jLabel10);

        txtTrx_type.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtTrx_type.setText("Mobil");
        jPanel7.add(txtTrx_type);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel11.setText("JAM MASUK");
        jPanel7.add(jLabel11);

        txtTrx_entrance.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtTrx_entrance.setText("06:30:15 21/10/2017");
        jPanel7.add(txtTrx_entrance);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel12.setText("JAM KELUAR");
        jPanel7.add(jLabel12);

        txtTrx_Exit.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtTrx_Exit.setText("06:30:15 21/10/2017");
        jPanel7.add(txtTrx_Exit);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel13.setText("TOTAL BIAYA");
        jPanel7.add(jLabel13);

        txtTrx_Price.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtTrx_Price.setText("Rp. 11.000.-");
        jPanel7.add(txtTrx_Price);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TRANSAKSI KENDARAAN");

        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 300, 0));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("(Dummy) Tap Card");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        btnCancelPayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCancelPayment.setText("BATAL");
        btnCancelPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelPaymentActionPerformed(evt);
            }
        });
        jPanel5.add(btnCancelPayment);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1018, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("SILAKAN TAP KARTU PEMBAYARAN ANDA !");

        javax.swing.GroupLayout jPanel4_paymentLayout = new javax.swing.GroupLayout(jPanel4_payment);
        jPanel4_payment.setLayout(jPanel4_paymentLayout);
        jPanel4_paymentLayout.setHorizontalGroup(
            jPanel4_paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4_paymentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4_paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4_paymentLayout.createSequentialGroup()
                        .addGap(0, 179, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4_paymentLayout.setVerticalGroup(
            jPanel4_paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4_paymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_main.add(jPanel4_payment, "card_payment");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("TERIMA KASIH");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("WAKTU ANDA 15 MENIT UNTUK KELUAR DARI GERBANG !!!");

        jPanel12.setLayout(new java.awt.GridLayout(2, 2));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel16.setText("TOTAL BIAYA");
        jPanel12.add(jLabel16);

        txtFin_Price.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtFin_Price.setText("Rp. 11.000.-");
        jPanel12.add(txtFin_Price);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel17.setText("SISA SALDO");
        jPanel12.add(jLabel17);

        txtFin_balance.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtFin_balance.setText("Rp. 154.000.-");
        jPanel12.add(txtFin_balance);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                    .addContainerGap(217, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_finishLayout = new javax.swing.GroupLayout(jPanel_finish);
        jPanel_finish.setLayout(jPanel_finishLayout);
        jPanel_finishLayout.setHorizontalGroup(
            jPanel_finishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_finishLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_finishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_finishLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_finishLayout.setVerticalGroup(
            jPanel_finishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_finishLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_main.add(jPanel_finish, "card_finish");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar_Step, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar_Step, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String code = JOptionPane.showInputDialog("Barcode :");
        if (!code.equals("")) {
            //Isi Objek Tiket dengan data dari database
            getDataTicket(code);
            //Tampil Info Parkit
            cl = (CardLayout) jPanel_main.getLayout();
            cl.show(jPanel_main, "card_parkingInfo");
        } else {
            System.out.println("Barcode tidak ditemukan");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCancelInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelInfoActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) jPanel_main.getLayout();
        cl.show(jPanel_main, "card_scan");
    }//GEN-LAST:event_btnCancelInfoActionPerformed

    private void btnPaymentProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentProcessActionPerformed
        // TODO add your handling code here:
        //Proses data tiket menjadi informasi pembayaran
        getDataPayment(tkt.getBarcode());
        cl = (CardLayout) jPanel_main.getLayout();
        cl.show(jPanel_main, "card_payment");
    }//GEN-LAST:event_btnPaymentProcessActionPerformed

    private void btnCancelPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelPaymentActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) jPanel_main.getLayout();
        cl.show(jPanel_main, "card_parkingInfo");
    }//GEN-LAST:event_btnCancelPaymentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) jPanel_main.getLayout();
        cl.show(jPanel_main, "card_finish");
        try {
            //Capture Webcam (2 Option with different Library)
            //Pilihan 1
            //boolean c = new Camera().capture(tkt.getBarcode());
            //Pilihan 2
            new WebcamCapture().capture(tkt.getBarcode());
        } catch (IOException ex) {
            Logger.getLogger(Hexapark_backup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnChangePolNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePolNumActionPerformed
        // TODO add your handling code here:
        //Update Nomor Polisi Kendaraan
        int updatePolNum = new queryTicket().updatePolNum(tkt.getBarcode(), tkt_noPol.getText());
        if (updatePolNum != 0) {
            tkt.setLicenseNumber(tkt_noPol.getText());
            JOptionPane.showMessageDialog(null, "Nomor Polisi Berhasil Diperbarui");
        } else {
            JOptionPane.showMessageDialog(null, "Nomor Polisi Gagal Diperbarui, Silakan Hubungi Pengelola Layanan");
        }
    }//GEN-LAST:event_btnChangePolNumActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) jPanel_main.getLayout();
        cl.show(jPanel_main, "card_scan");
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void getDataTicket(String code) {
        tkt = new queryTicket().getData(code);
        tkt_barcode.setText(code);
        tkt_gate.setText(Integer.toString(tkt.getEntranceGate()));
        tkt_entrance.setText(tkt.getEntranceTime());
        tkt_noPol.setText(tkt.getLicenseNumber());
        
        //Testing Cek Harga
        queryPayment qp = new queryPayment();
        int[] tarifInfo = qp.getPriceInfo(tkt);
        System.out.println("Tarif Info");
        System.out.print(tarifInfo[0]+" ");
        System.out.print(tarifInfo[1]+" ");
        System.out.print(tarifInfo[2]+" ");
        System.out.println(tarifInfo[3]);
        int harga=0;
        if(qp.cekMember(tkt.getBarcode()).equalsIgnoreCase("YES")){
            System.out.println("Member Mah Gratis");
        }else if(tkt.getTarifTypes().equalsIgnoreCase("I A")){
            System.out.println(tkt.getTarifTypes());
        }else if(tkt.getTarifTypes().equalsIgnoreCase("I B")){
            System.out.println(tkt.getTarifTypes());
        }else if(tkt.getTarifTypes().equalsIgnoreCase("I C")){
            System.out.println(tkt.getTarifTypes());
        }else if(tkt.getTarifTypes().equalsIgnoreCase("III A")){
            System.out.println(tkt.getTarifTypes());
            harga = qp.determinePriceInap(tkt.getEntranceTime(), tkt.getExitTime(), tarifInfo[1], tarifInfo[2], tarifInfo[0]);
        }else if(tkt.getTarifTypes().equalsIgnoreCase("IV")){
            System.out.println(tkt.getTarifTypes());
            harga = qp.determinePriceInap(tkt.getEntranceTime(), tkt.getExitTime(), tarifInfo[1], tarifInfo[2], tarifInfo[0]);
        }
        System.out.println(harga);
    }

    private void getDataPayment(String code) {
        txtTrx_Gate.setText(Integer.toString(tkt.getEntranceGate()));
        txtTrx_PolNum.setText(tkt.getLicenseNumber());
        txtTrx_type.setText(tkt.getVehicleTypes());
        txtTrx_entrance.setText(tkt.getEntranceTime());
        //Set Date Exit
        Calendar dateNow = Calendar.getInstance();
        Date skr = new Date();
        dateNow.setTime(skr);
        txtTrx_Exit.setText(exitTime.format(skr));
        txtTrx_Price.setText("RP." + tkt.getPrice() + ".-");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hexapark_backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hexapark_backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hexapark_backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hexapark_backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hexapark_backup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelInfo;
    private javax.swing.JButton btnCancelPayment;
    private javax.swing.JButton btnChangePolNum;
    private javax.swing.JButton btnPaymentProcess;
    private javax.swing.JButton btn_finish;
    private javax.swing.JButton btn_parkingInfo;
    private javax.swing.JButton btn_payment;
    private javax.swing.JButton btn_scanTiket;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel4_payment;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_finish;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPanel jPanel_parkingInfo;
    private javax.swing.JPanel jPanel_scan;
    private javax.swing.JToolBar jToolBar_Step;
    private javax.swing.JLabel tkt_barcode;
    private javax.swing.JLabel tkt_entrance;
    private javax.swing.JLabel tkt_gate;
    private javax.swing.JTextField tkt_noPol;
    private javax.swing.JLabel txtFin_Price;
    private javax.swing.JLabel txtFin_balance;
    private javax.swing.JLabel txtTrx_Exit;
    private javax.swing.JLabel txtTrx_Gate;
    private javax.swing.JLabel txtTrx_PolNum;
    private javax.swing.JLabel txtTrx_Price;
    private javax.swing.JLabel txtTrx_entrance;
    private javax.swing.JLabel txtTrx_type;
    // End of variables declaration//GEN-END:variables
}
